name: Doxygen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.9.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          doxyfile-path: Documentation/Doxyfile
